services:
    mysql:
        build:
            context: ./.docker/mysql
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fastapi
            MYSQL_USER: fastapi
            MYSQL_PASSWORD: B^2!L@Y8cMy*3^tP3dCujVijYaLq#^Gt
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

networks:
    backend:
volumes:
    mysql_data:
