# https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
    mysql:
        image: fastapi-mysql:2024.10.12-001
        # https://docs.docker.com/reference/compose-file/build/
        build:
            context: ./.docker/mysql
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fastapi
            MYSQL_USER: fastapi
            MYSQL_PASSWORD: B^2!L@Y8cMy*3^tP3dCujVijYaLq#^Gt
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

networks:
    backend:
volumes:
    mysql_data:
